title: Tamer Samara
logo: "/images/tamerpic.png?raw=true"
description: >
   Dedicated data analyst skilled in extracting meaningful patterns from diverse datasets.
   Expertise in statisitical analysis, data modeling, and visualization tools.
   Committed to optimizing bussiness processes and facilitating data-driven decisions 
   for enhanced organizational success. 
   <br><br>
   <a href="https://www.linkedin.com/in/tamergeorgesamara/">View My LinkedIn Profile</a> 
   
theme: jekyll-theme-minimal

google_analytics: G-FFBFKN9WD5
