title: Tamer Samara
logo: "/images/tamerpic.png?raw=true"
description: >
   My name is Tamer, and I'm a python programmer looking to flex my talents to identify 
   new growth strategies as a Junior Data Analyst.
   <br><br>
   I've always been fascinated by numbers, and working in data analytics has been a long-term goal of mine.
   My career in digital marketing has taught me to think strategically about problems and identify solutions.
   <br><br>
   <a href="https://www.linkedin.com/in/tamergeorgesamara/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
