title: Tamer Samara
logo: "/images/tamerpic.png?raw=true"
description: >
   My name is Tamer, A motivated and detail-oriented junior data analyst seeking a challenging position 
   where I can utilize my analytical skills and passion for data to contribute to the success 
   of a dynamic organization.
   <br><br>
   <a href="https://www.linkedin.com/in/tamergeorgesamara/">View My LinkedIn Profile</a> 
   
theme: jekyll-theme-minimal

google_analytics: <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FFBFKN9WD5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FFBFKN9WD5');
</script>
