title: Tamer Samara
logo: "/images/tamerpic.png?raw=true"
description: >
   My name is Tamer, and I'm a python programmer looking to flex my talents to identify 
   new growth strategies as a Junior Data Analyst.
   <br><br>
   <a href="https://www.linkedin.com/in/tamergeorgesamara/">View My LinkedIn Profile</a> 
   <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
