title: Tamer Samara
logo: "/images/tamerpic.png?raw=true"
description: > 
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/tamergeorgesamara/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
